version: "3"
services:
  app:
    build: .
    command: run dev
    depends_on:
      - elasticsearch
      - mysql
    links:
      - elasticsearch
      - mysql
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_PROTO=http
      - NODE_ENV=development
    env_file: .env
    image: usersdata
    network_mode: bridge
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    volumes:
      - ./:/code
      - /code/node_modules
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    network_mode: bridge
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  mysql:
    env_file: .env
    expose:
      - 3306
      - 5218
    image: mysql:5.7
    network_mode: bridge
    ports:
      - 5218:3306
